PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#> 
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> 
PREFIX rhea: <http://rdf.rhea-db.org/>

CONSTRUCT {

  ?r a owl:Class ;
     rdfs:subClassOf ?p ;
     rdfs:label ?e
}
WHERE {
  ?r <http://www.w3.org/2000/01/rdf-schema#subClassOf> rhea:Reaction .
  ?r rhea:equation ?e .
  ?r <http://www.w3.org/2000/01/rdf-schema#subClassOf> ?p
}
